### ISSUE TITLE
How to Deploy

### ISSUE THREAD

**Issue by bbrooks870** [Atuldubey98/movies-downloader#1]
Can you make it dockerise or little guide on how to deploy on  vps or render

**Comment by Atuldubey98** [comment]
Hi @bbrooks870, I will do it and let you know.

**Comment by Atuldubey98** [comment]
Hi @bbrooks870 , I have fixed the issues. Please check the ReadMe file. I have updated the same as well.
- Create a .env file in the project folder like .env.example
- Create a .env file in render like .env in project directory we have just created.
- Use Docker to create a project in Render
- In Health check path write /api/v1/health
- Now in Dockerfile path write ./Dockerfile.prod
- Deploy the service.

I even create a prod and dev stage configuration for docker. Please refer those.

If you find any thing confusing, Please feel free to contact me.

**Comment by Atuldubey98** [comment]
Hi @bbrooks870, Did you get the chance to deploy the application?
