### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by segseaweber** [Atuldubey98/movies-downloader#2]
can i have your handle for paid task

**Comment by Atuldubey98** [comment]
Hey, 

Can you tell me what do I need to do for this?

**Comment by segseaweber** [comment]
Oh I don’t know you’ve replied me, I need a movie downloader , that will be
automatic using tmdb directory i.e domain.com/movie/tmdb_id

**Comment by Atuldubey98** [comment]
Okay can you please setup a call for this? I need to know what is your actual requirement. You can setup call at 11:00 am IST.

**Comment by segseaweber** [comment]
Please give me your telegram or number

Here is a demo of what i need
https://dl.vidsrc.vip/m/tt27440937

**Comment by Atuldubey98** [comment]
Here is my telegram user id Atuldubey017.![Screenshot_20240812_133630_Telegram.jpg](https://github.com/user-attachments/assets/f1021751-66dd-4fa0-9687-bfd42556efd9)

**Comment by segseaweber** [comment]
Check your telegram
